### ISSUE TITLE
Install error: from PIL import ImageTk

### ISSUE THREAD

**Issue by gamesbook** [adasilva/journal2ebook#32]
I have cloned the project into a directory; but when I try python journal2ebook.py , I get this error:
```
from PIL import ImageTk
ImportError: cannot import name ImageTk
```
I am running Python 2.7.6 (default, Mar 22 2014, 22:59:56), under Ubuntu 14.04

PIL.VERSION shows 1.1.7

**Comment by gamesbook** [comment]
OK; found a fix - run:
```
sudo apt-get install python-imaging-tk
```

**Comment by adasilva** [comment]
Great! Thanks for reporting your fix.

**Comment by abdulkalam1233** [comment]
for python3 : sudo apt-get install python3-pil.imagetk

**Comment by anish-chapagai** [comment]
@gamesbook Thanks! Worked for me.

**Comment by saikiran994** [comment]
sudo apt-get install python3-pil.imagetk

above command is not working

**Comment by abdulkalam1233** [comment]
> sudo apt-get install python3-pil.imagetk
> 
> above command is not working

https://howtoinstall.co/en/ubuntu/xenial/python3-pil.imagetk

**Comment by GavinGit311hub** [comment]
how about window? Is it like this?: pip install python3-pil.imagetk.

**Comment by VictorCubas** [comment]
how about in fedora?
