### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by cgahr** [adasilva/journal2ebook#34]
Hi,
is this project still alive?

Personally, I'm interested in this project and could look into updating it to python3 etc.

BR,
Constantin

**Comment by Alcamis** [comment]
Hi, yes indeed it has just been accepted for publication. 
Please let me know if I can help with your update.
(There is also supplementary material)
Thanks!

**Comment by ConstantinGahr** [comment]
For personal usage, I completely rewrote the whole application. I could make my changes publically available, however I would need some feedback from the owners first.

**Comment by adasilva** [comment]
Hi @cgahr please feel free to make your changes available. I am no longer actively updating this project.
